Repository AY2223S1-CS2103-F13-1/tp, pull requests merged in 2022-10, with the labels that each got.

#62 Create project component classes
  src/main/java/seedu/address/model/project/Deadline.java
  src/main/java/seedu/address/model/project/Name.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/Repository.java
  src/test/java/seedu/address/model/project/DeadlineTest.java
  src/test/java/seedu/address/model/project/NameTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/model/project/RepositoryTest.java
Labels: type.Task, priority.High

#66 Add Client Class
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/client/Client.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Task, priority.High

#65 Refactor UI & Storage to accomodate Project and Issue
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/project/Deadline.java
  src/main/java/seedu/address/model/project/Repository.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/project/RepositoryTest.java
Labels: type.Task, priority.Medium

#72 Create Client Package
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/ClientEmail.java
  src/main/java/seedu/address/model/client/ClientId.java
  src/main/java/seedu/address/model/client/ClientName.java
  src/main/java/seedu/address/model/client/ClientPhone.java
  src/main/java/seedu/address/model/client/ClientProjectList.java
  src/main/java/seedu/address/model/client/Type.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/client/exceptions/ClientNotFoundException.java
  src/main/java/seedu/address/model/client/exceptions/DuplicateClientException.java
  src/main/java/seedu/address/model/person/client/Client.java
  src/main/java/seedu/address/model/project/Project.java
  src/test/java/seedu/address/model/client/ClientEmailTest.java
  src/test/java/seedu/address/model/client/ClientNameTest.java
  src/test/java/seedu/address/model/client/ClientPhoneTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
Labels: type.Task, priority.High

#78 Edit help command URL
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.Low

#80 Add issue command
  .gitignore
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/issue/AddIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/DeleteIssueCommand.java
  src/main/java/seedu/address/logic/parser/IssueCliSyntax.java
  src/main/java/seedu/address/logic/parser/IssueCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Deadline.java
  src/main/java/seedu/address/model/issue/Description.java
  src/main/java/seedu/address/model/issue/Issue.java
  src/main/java/seedu/address/model/issue/IssueId.java
  src/main/java/seedu/address/model/issue/Priority.java
  src/main/java/seedu/address/model/issue/Status.java
  src/main/java/seedu/address/model/issue/UniqueIssueList.java
  src/main/java/seedu/address/model/project/UniqueProjectList.java
  src/main/java/seedu/address/storage/JsonAdaptedIssue.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/IssueCard.java
Labels: priority.High

#79 B add project
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/issue/AddIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/DeleteIssueCommand.java
  src/main/java/seedu/address/logic/commands/project/AddProjectCommand.java
  src/main/java/seedu/address/logic/commands/project/DeleteProjectCommand.java
  src/main/java/seedu/address/logic/commands/project/ListProjectCommand.java
  src/main/java/seedu/address/logic/parser/IssueCliSyntax.java
  src/main/java/seedu/address/logic/parser/IssueCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProjectCliSyntax.java
  src/main/java/seedu/address/logic/parser/ProjectCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Deadline.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/Name.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/ClientEmail.java
  src/main/java/seedu/address/model/client/ClientId.java
  src/main/java/seedu/address/model/client/ClientPhone.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/issue/UniqueIssueList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/ProjectId.java
  src/main/java/seedu/address/model/project/Repository.java
  src/main/java/seedu/address/model/project/UniqueProjectList.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ProjectCommandParserTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
Labels: priority.High

#83 Implement Client Commands
  src/main/java/seedu/address/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/client/DeleteClientCommand.java
  src/main/java/seedu/address/logic/parser/ClientCliSyntax.java
  src/main/java/seedu/address/logic/parser/ClientCommandParser.java
  src/main/java/seedu/address/model/Name.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/ClientId.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/ProjectId.java
  src/main/java/seedu/address/model/project/UniqueProjectList.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#96 Edit Issue Command
  src/main/java/seedu/address/logic/commands/issue/EditIssueCommand.java
  src/main/java/seedu/address/logic/commands/project/EditProjectCommand.java
  src/main/java/seedu/address/logic/parser/IssueCliSyntax.java
  src/main/java/seedu/address/logic/parser/IssueCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/issue/Issue.java
  src/main/java/seedu/address/model/issue/IssueId.java
  src/main/java/seedu/address/model/issue/Priority.java
  src/main/java/seedu/address/model/issue/UniqueIssueList.java
Labels: priority.High

#101 Fix bug where default values were incorrectly loaded from storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Deadline.java
  src/main/java/seedu/address/model/Name.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/ClientEmail.java
  src/main/java/seedu/address/model/client/ClientId.java
  src/main/java/seedu/address/model/client/ClientPhone.java
  src/main/java/seedu/address/model/issue/Description.java
  src/main/java/seedu/address/model/issue/Issue.java
  src/main/java/seedu/address/model/issue/IssueId.java
  src/main/java/seedu/address/model/issue/Priority.java
  src/main/java/seedu/address/model/list/UniqueEntityList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/ProjectId.java
  src/main/java/seedu/address/model/project/Repository.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonAdaptedIssue.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Bug, severity.Medium

#106 Update developer guide with list command implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ListActivityDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/images/ListActivityDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/team/skeletal_ppp.md
Labels: type.Documentation

#104 Implement default view commands
  src/main/java/seedu/address/commons/core/DefaultView.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/client/SetClientDefaultViewCommand.java
  src/main/java/seedu/address/logic/commands/issue/SetIssueDefaultViewCommand.java
  src/main/java/seedu/address/logic/commands/project/SetProjectDefaultViewCommand.java
  src/main/java/seedu/address/logic/parser/ClientCommandParser.java
  src/main/java/seedu/address/logic/parser/IssueCommandParser.java
  src/main/java/seedu/address/logic/parser/ProjectCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/client/SetClientDefaultViewCommandTest.java
  src/test/java/seedu/address/logic/commands/issue/SetIssueDefaultViewCommandTest.java
  src/test/java/seedu/address/logic/commands/project/SetProjectDefaultViewCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task, priority.Low

#116 Add Edit Command in Developers Guide
  docs/DeveloperGuide.md
Labels: priority.Medium

#115 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#108 Sort, bugs and developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/issue/DeleteIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/EditIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/SortIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/find/FindIssueCommand.java
  src/main/java/seedu/address/logic/commands/project/DeleteProjectCommand.java
  src/main/java/seedu/address/logic/commands/project/EditProjectCommand.java
  src/main/java/seedu/address/logic/commands/project/SortProjectCommand.java
  src/main/java/seedu/address/logic/parser/ClientCliSyntax.java
  src/main/java/seedu/address/logic/parser/IssueCliSyntax.java
  src/main/java/seedu/address/logic/parser/IssueCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProjectCliSyntax.java
  src/main/java/seedu/address/logic/parser/ProjectCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Deadline.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/issue/Issue.java
  src/main/java/seedu/address/model/issue/IssueId.java
  src/main/java/seedu/address/model/list/UniqueEntityList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/ProjectId.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/ui/StubUiManager.java
Labels: type.Task, priority.Medium

#127 Gui
  src/main/java/seedu/address/model/client/ClientPhone.java
  src/main/java/seedu/address/model/project/Repository.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/IssueCard.java
  src/main/java/seedu/address/ui/IssueListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/java/seedu/address/ui/ProjectListPanel.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/devenable.png
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/ClientListPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DevEnable.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/IssueListCard.fxml
  src/main/resources/view/IssueListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProjectListCard.fxml
  src/main/resources/view/ProjectListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/model/project/RepositoryTest.java
Labels: priority.High

#130 Update User Guide
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/client/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/client/EditClientCommand.java
Labels: priority.Medium, type.Documentation

#129 Restructure Find Commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/client/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/client/FindClientCommand.java
  src/main/java/seedu/address/logic/commands/client/ListClientCommand.java
  src/main/java/seedu/address/logic/commands/client/find/FindClientByEmailCommand.java
  src/main/java/seedu/address/logic/commands/client/find/FindClientByNameCommand.java
  src/main/java/seedu/address/logic/commands/client/find/FindClientByPhoneCommand.java
  src/main/java/seedu/address/logic/commands/client/find/FindClientCommand.java
  src/main/java/seedu/address/logic/commands/issue/FindIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/find/FindIssueByPriorityCommand.java
  src/main/java/seedu/address/logic/commands/issue/find/FindIssueByProjectCommand.java
  src/main/java/seedu/address/logic/commands/issue/find/FindIssueByStatusCommand.java
  src/main/java/seedu/address/logic/commands/issue/find/FindIssueByTitleCommand.java
  src/main/java/seedu/address/logic/commands/issue/find/FindIssueCommand.java
  src/main/java/seedu/address/logic/commands/project/FindProjectCommand.java
  src/main/java/seedu/address/logic/commands/project/find/FindProjectByNameCommand.java
  src/main/java/seedu/address/logic/commands/project/find/FindProjectByRepositoryCommand.java
  src/main/java/seedu/address/logic/commands/project/find/FindProjectCommand.java
  src/main/java/seedu/address/logic/parser/ClientCommandParser.java
  src/main/java/seedu/address/logic/parser/IssueCliSyntax.java
  src/main/java/seedu/address/logic/parser/IssueCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/predicates/ClientContainsKeywordsPredicate.java
  src/main/java/seedu/address/logic/parser/predicates/IssueContainsKeywordsPredicate.java
  src/main/java/seedu/address/logic/parser/predicates/ProjectContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/predicates/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/issue/Priority.java
  src/main/java/seedu/address/model/issue/Status.java
  src/main/java/seedu/address/model/issue/predicates/PriorityMatchesKeywordsPredicate.java
  src/main/java/seedu/address/model/issue/predicates/ProjectContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/issue/predicates/StatusMatchesKeywordsPredicate.java
  src/main/java/seedu/address/model/project/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/project/predicates/RepositoryContainsKeywordsPredicate.java
Labels: priority.High

#140 Minor UI Fixes
  src/main/resources/view/DevEnable.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low, type.Bug

#145 Update UG to match new find commands
  docs/UserGuide.md
Labels: type.Documentation

#147 Add Section Headings
  docs/UserGuide.md
Labels: priority.Low, type.Documentation
