Repository AY2223S1-CS2103-F13-1/tp, pull requests merged in 2022-09, with the labels that each got.

#16 Update aboutUs.md and include member photos
  docs/AboutUs.md
  docs/images/aishwarya-hariharan-iyer.png
  docs/images/conradlew.png
  docs/images/crvstalphua.png
  docs/images/donovan9617.png
  docs/images/yongbeom-kim.png
  docs/team/aishwarya-hariharan-iyer.md
  docs/team/conradlew.md
  docs/team/crvstalphua.md
  docs/team/donovan9617.md
  docs/team/yongbeom-kim.md
Labels: type.Task

#19 Update content for site header
  docs/_sass/minima/_base.scss
Labels: documentation, type.Task

#25 Update developer guide
  docs/DeveloperGuide.md
Labels: documentation, type.Task

#23 Update UG.md
  docs/UserGuide.md
Labels: documentation, type.Task

#21 Update README.md
  README.md
Labels: documentation, type.Task

#28 Updated Glossary, User Profile, Value Proposition
  docs/DeveloperGuide.md
Labels: documentation
